hasura/promptql-docs

- docs/help/glossary.mdx
- docs/help/overview.mdx
- docs/help/security.mdx
Rewrites Help section for PromptQL.
One question that needs to be addressed: Here, we're still referring to the v3 engine (especially in the policies and versioning sections). Is this piece of the stack still relevant? Conventional wisdom says, 'yes', but we need to confirm this.
> Rewrite Help section for PromptQL

- docs/promptql-apis/natural-language-api.mdx
- docs/promptql-playground/public-projects.mdx
We recently updated the number of credits to $20 ( [commit](https://github.com/hasura/promptql-cloud/pull/261) )
Also - we need to nudge the users to talk to sales to upgrade their trials.
> Updated the number of credits, and text based on PromptQL GTM

- docs/business-logic/dev-mode.mdx
- docs/business-logic/errors.mdx
Adds docs for iterating with Lambda connectors using Compose Watch.
This has been validated and tested across each Lambda connector with caveats for varying directory structures, etc.
[Live Reloading with Compose Watch](https://robdominguez-doc-2684-add-in.promptql-docs.pages.dev/business-logic/dev-mode/)
> Add docs for iterating with Lambda connectors

- docs/promptql-apis/auth.mdx
- docs/promptql-apis/execute-program-api.mdx
- docs/promptql-apis/natural-language-api.mdx
- docs/promptql-apis/overview.mdx
Improves information for APIs by adding examples for requests and responses and by introducing an explicit section for authentication when using PromptQL.
[API Overview](https://robdominguez-doc-2685-add-in.promptql-docs.pages.dev/promptql-apis/overview/)
A user should understand the shape of requests and responses from these endpoints and how to utilize their auth mechanism of choice via DDN.
> Improve information for APIs

- docs/project-configuration/project-management/console-collaborator-comments.mdx
- docs/project-configuration/project-management/manage-environment-variables.mdx
Adds information for managing environment variables. Notably, we've provided guidance on the differences between local and cloud env files while also directing users to utilize CI/CD when creating cloud deployments to avoid issues with conflicts in their .env.cloud files.
[Manging Environment Variables](https://robdominguez-doc-2690-improv.promptql-docs.pages.dev/project-configuration/project-management/manage-environment-variables/)
> Add information for managing environment variables

- .github/workflows/migrate-to-ddn.yml
Adds workflow for syncing changes from promptql-docs to ddn. All `bash`. Fast.
Workflow: 
- On PR merge with label `migrate-to-ddn`
- breaks commit to promptql-docs main into patches per file
- Create new branch on ddn-docs
- Create new draft PR for branch with title and details etc
- Loop through patches and try to apply to branch
- If a patch fails add comment to the PR with patch diff information
- Assign PR and un-draft if no failures. Keep draft with failures
[Link to Linear issue with demo.](https://linear.app/hasura/issue/DOC-2717/add-an-action-that-syncs-promptql-%C2%BB-ddn-docs)
/.github/workflows/migrate-to-ddn.yml
> Adds workflow for syncing changes from promptql-docs to ddn

- docs/data-sources/connect-to-a-source.mdx
Adds a note to escape special chars in connection strings.
> Escape special chars in connections strings. 

- docs/business-logic/errors.mdx
Adds a response-size limitations section for lambdas. Currently, the nodejs connector is the only one included here; it was easily discoverable in the underlying TS SDK. However, I'm not sure about the Python and Go SDKs...I've reached out to Toan for more information.
EDIT: ☝️ The others will follow the TS implementation.
[New section](https://robdominguez-doc-2773-docume.promptql-docs.pages.dev/business-logic/errors/#response-size-limitations)
> Add response-size limitations for lambdas

- .github/workflows/open-redirects-pr.yml
- .github/workflows/run-changelog-for-field-teams.yml
* Updates the redirects Action to reference PQL instead of DDN
* Update field-team notification
* Update redirect logic
Updates redirect logic to deal with what seems to be a race condition. As an example, earlier in the week, I noticed that this run missed the PR for the changes in the lambda directory: https://github.com/hasura/promptql-docs/actions/runs/15070798392/job/42366355757
> CI: Update actions

- .prettierrc.json
- docusaurus.config.ts
- src/css/custom.css
- The fonts weren't actually loading. It was because the `stylesheets` prop was in the wrong place in docusaurus config.
- Fonts in the design are enormous when used at that size on the real site. Have downscaled a bit. CC: @surendran82 
- Left sidebar titles were quite different to the design. 
- Corrected font, size (a bit), and color
**Before:**
**After:**
- Fix font color
**Before:**
**After:**
- Size and color to be consistent with design. (Size taken down a bit because design is huge on site)
**Before:**
**After:**
- Bump heading sizes to be more like designs
**Before:**
**After:**
- Remove tabs left right padding as per design
**After:**
- Knocked back color looked very strange changed to text color for now
- The primary neutral colors in the CSS are still from Tailwind defaults. …
> Sean Theme tweaks => Merging to robs theme => Merging to blitz

- docusaurus.config.ts
Updates the config to use the `/docs` path instead of `/docs/promptql` as the new entrypoint for docs will be `https://promptql.io/docs` and `/docs/promptql` was quite redundant.
> Chore: Update config

- docs/project-configuration/promptql-config/providers.mdx
- docs/project-configuration/promptql-config/system-instructions.mdx
- docs/reference/metadata-reference/promptql-config.mdx
- Update PromptQlConfig version to v2 in How To docs
- Update system instructions version in PromptQlConfig from v1 to v2 in How to Docs
- Update promptql-config in Reference
[/project-configuration/promptql-config/providers](https://sean-fix-promptql-version.promptql-docs.pages.dev/project-configuration/promptql-config/providers/)
[/project-configuration/promptql-config/system-instructions](https://sean-fix-promptql-version.promptql-docs.pages.dev/project-configuration/promptql-config/system-instructions/)
[/reference/metadata-reference/promptql-config](https://sean-fix-promptql-version.promptql-docs.pages.dev/reference/metadata-reference/promptql-config/)
> Update promptql metadata version from v1 to v2

- docusaurus.config.ts
- src/components/Feedback/Feedback.tsx
Fixes feedback component by modifying the endpoint.
Currently, the concatenated URL for the fetch here is 
```
https://website-api.hasura.io/feedback/public-new-feedback?
```
Which returns a `404`. The service actually lives at:
```
https://website-api.hasura.io/docs-services/docs-server/feedback/public-new-feedback
```
I've made the modification in this fetch because I'm not 100% sure where else `docsServerURL` is used and don't want to cause disruptions to other components.
If this is accurate, it will need to be ported to `hasura/ddn-docs`.
> Fix: Feedback component

- docs/auth/jwt/jwt-configuration.mdx
- docs/auth/jwt/jwt-mode.mdx
- docs/auth/jwt/tutorials/integrations/1-auth0.mdx
- docs/auth/jwt/tutorials/integrations/2-aws-cognito.mdx
- docs/auth/jwt/tutorials/integrations/3-firebase.mdx
- docs/auth/jwt/tutorials/integrations/4-clerk.mdx
- docs/auth/jwt/tutorials/setup-test-jwt.mdx
- docs/auth/multiple-auth-modes.mdx
- docs/auth/noauth-mode.mdx
- docs/auth/overview.mdx
- docs/auth/webhook/webhook-mode.mdx
- docs/project-configuration/project-management/manage-environments.mdx
- docs/reference/metadata-reference/auth-config.mdx
This PR adds docs for multiple auth mode support introduced in `AuthConfig` v4.
- Updated the occurrences of AuthConfig v3 to AuthConfig v4
- Added a docs page on multiple auth mode
Multiple Auth Mode page: https://paritosh-auth-config-v4.promptql-docs.pages.dev/auth/multiple-auth-modes/
> docs for `AuthConfig` v4 (multiple auth mode support)

- docs/data-modeling/typecasting.mdx
Adds a guide for recasting types using a string » int example.
This has been validated using a sample Postgres schema that has the following shape:
```sql
CREATE TABLE "public"."order_items" (
"id" integer DEFAULT nextval('order_items_id_seq') NOT NULL,
"order_id" integer NOT NULL,
"product_name" character varying(255) NOT NULL,
"quantity_text" text NOT NULL,
"price_text" text NOT NULL,
"category_code" text NOT NULL,
CONSTRAINT "order_items_pkey" PRIMARY KEY ("id")
)
INSERT INTO "order_items" ("id", "order_id", "product_name", "quantity_text", "price_text", "category_code") VALUES
(1,	1001,	'Laptop',	'2',	'999.99',	'1'),
(2,	1001,	'Mouse',	'1',	'25.50',	'2'),
(3,	1002,	'Monitor',	'1',	'299.99',	'1'),
(4,	1002,	'Keyboard',	'3',	'75.00',	'2'),
(5,	1003,	'Tablet',	'1',	'499.99',	'1'),
(6, …
```
> Docs: Add typecasting guide

- docs/automation.mdx
- docs/decision-making.mdx
- docs/how-to-talk-to-promptql.mdx
Adds a how-to-talk to PromptQL section.
This is primarily based off work with the ACT folks and from being embedded with them in conversations to end users. This section will expand, but for now, it covers a very quick read that we can provide as collateral to end users who are first exploring the product.
[How to Talk to PromptQL](https://add-what-can-pql-do.promptql-docs.pages.dev/how-to-talk-to-promptql/)
> Docs: Add how-to-talk section

- .gitignore
- docs/automation.mdx
- docs/capabilities.mdx
- docs/decision-making.mdx
- docs/how-to-talk-to-promptql.mdx
- src/css/custom.css
- src/theme/DocRoot/Layout/Sidebar/styles.module.css
- src/theme/DocSidebar/CustomSidebar.css
- src/theme/DocSidebar/Desktop/CollapseButton/index.tsx
- src/theme/DocSidebar/Desktop/CollapseButton/styles.module.css
- src/theme/DocSidebar/Desktop/Content/index.tsx
- src/theme/DocSidebar/Desktop/Content/styles.module.css
- src/theme/DocSidebar/Desktop/index.tsx
- src/theme/DocSidebar/Desktop/styles.module.css
- src/theme/DocSidebar/Mobile/index.tsx
- src/theme/DocSidebar/categories.ts
- src/theme/DocSidebar/index.tsx
- src/theme/DocSidebar/utils.ts
This PR adds a fully custom sidebar implementation for our docs, giving us complete control over structure, styling, and behavior. I replaced the default layout with a custom React component that uses a category config to group and order pages consistently, cleaned up sidebar labels, and improved visual clarity with a redesigned CSS file. 
This sets us up for more flexible sidebar behavior going forward.
> Feature: Customize sidebar

- docs/capabilities.mdx
- docs/decision-making.mdx
- docs/how-to-talk-to-promptql.mdx
> Docs: Language pass

- docs/architecture.mdx
- src/theme/DocSidebar/categories.ts
Adds a page for Architecture that's purposefully very broad.
If you take a peek at the categories in the sidebar, we enter with the quickstart for end users and then build by talking about capabilities, steering, and use cases.
This is the first page in the Core Concepts section and is meant to be as high-level of an overview as possible. We could—and should—introduce a section within this page that highlights differences between the data and control planes. But, for now, this simply serves to illustrate the various services that are running and how they work together to produce the end-user experience.
An easy way to think of this: what's (relevant) in the root `compose.yaml` and what does each service do?
[Architecture](https://robdominguez-doc-2910-add-ar.promptql-docs.pages.dev/archite …
> Docs: Add Architecture page

- docs/promptql-apis/execute-program-api.mdx
This pull request introduces significant updates to the documentation for the Execute Program API, focusing on adding support for multiple API versions, improving structure, and enhancing clarity. Key changes include the introduction of API versioning (v1 and v2), detailed request and response specifications for each version, and additional guidance on DDN authentication and build selection.
- https://rakesh-pql-606-update-docs-w.promptql-docs.pages.dev/promptql-apis/execute-program-api/
> Update docs with v2 version of execute program api

- docs/metadata/guides/_category_.json
- docs/metadata/index.mdx
- docs/metadata/system-instructions.mdx
- docs/project-configuration/promptql-config/index.mdx
- docs/project-configuration/promptql-config/providers.mdx
Moves `system-instructions.mdx` to the `/metadata` directory after the relevant metadata objects. In subsequent commits, we'll build context on this page to make it clear what belongs in system instructions and what doesn't (i.e., what should be in relevant metadata objects' pages).
Adds details for system instructions by stealing what makes sense in the ACT folks' Confluence.
[System Instructions](https://robdominguez-doc-2957-create.promptql-docs.pages.dev/metadata/system-instructions/)
> Docs: Create best practices documentation for promptql metadata

- docs/promptql-playground/chats/chat-titles.mdx
This pull request updates the documentation for chat title functionality in the PromptQL Playground to include new customization options and detailed configuration instructions for title generation. The changes enhance clarity, add support for disabling title generation, and provide guidance on specifying custom LLMs for title generation.
> Add PromptQL thread title generation configuration documentation

- docs/reference/connectors/postgresql/configuration.mdx
Added client certificate configuration documentation to PostgreSQL connector reference
Previously, developers using the PostgreSQL connector with SSL client certificates were hitting cryptic JDBC connection errors because the driver expects certificates in specific formats. The documentation provided no guidance on this, leaving users to figure out the PKCS#8 requirement through trial and error.
[PG Config](https://robdominguez-doc-3023-docume.promptql-docs.pages.dev/reference/connectors/postgresql/configuration/#client-certificate-configuration)
> Docs: Add cert note for PostgreSQL

- src/components/Feedback/styles.module.css
• Fixed low-contrast text colors in feedback component that were making content difficult to read
• Resolved dark background input fields appearing in light mode
• Improved dark mode textarea visibility by adding proper contrast
Previously, the feedback section was using hardcoded neutral colors that created accessibility issues:
```css
.form h3 {
color: var(--primary-neutral-200); /* Too light */
}
.form input,
.form textarea {
color: var(--primary-neutral-200);
background-color: var(--primary-dark); /* Black bg in light mode */
}
.textAreaLabel p {
color: var(--primary-neutral-300); /* Very light gray */
}
```
**Light Mode**
**Dark Mode**
Now we're using semantic color variables that adapt properly to both themes:
```css
.form h3 {
color: var(--heading-color); /* Theme-aware heading …
```
> Chore: Fix issues with feedback components visibilty

- .github/workflows/sync-embeddings.yml
We've built a workflow that maintains its own embeddings through PromptQL automations.
- Automatically syncs documentation changes to vector embeddings via PromptQL automations
- Handles create, update, and delete operations for documentation pages
- Parses frontmatter and content from MDX/MD files for semantic search
- Uses three dedicated automation endpoints for complete CRUD operations
Previously, documentation changes lived in isolation - you'd update a page and hope someone remembered to refresh whatever search or AI system was consuming it.
Now, every merged PR triggers an intelligent sync process that parses changed documentation files and automatically calls the appropriate PromptQL automation endpoint:
````yaml path=.github/workflows/sync-embeddings.yml mode=EXCERPT
case …
```
> CI: Add sync automations for embeddings

- src/components/CopyLlmText/index.tsx
Previously, the `CopyLLM` component only offered two actions: copying the full docs content to clipboard and downloading it as a file. Users had no way to quickly share the direct URL to the compiled docs file.
````tsx path=src/components/CopyLlmText/index.tsx mode=EXCERPT
// Before: Only copy and download options
<button className={styles.dropdownItem} onClick={handleCopy}>
Copy all docs content to clipboard for use in LLM prompts
</button>
<button className={styles.dropdownItem} onClick={handleDownload}>
Download docs content
</button>
````
Now, there's a third option that copies the direct URL (`https://promptql.io/docs/llms-full.txt`) to the clipboard, complete with its own loading and success states.
````tsx path=src/components/CopyLlmText/index.tsx mode=EXCERPT
// After: Added URL …
```
> Add option for llms-full.txt URL

- docs/private-ddn/architecture/byoc.mdx
- docs/private-ddn/architecture/dedicated.mdx
- Replaced static architecture diagrams with interactive Mermaid flowcharts for BYOC and Dedicated deployment modes
- Enhanced documentation accessibility for DocsQL by making diagrams machine-readable
- Maintained visual consistency across both deployment architectures
Previously, our Private DDN architecture documentation relied on static PNG images that were invisible to our DocsQL service:
````mdx path=docs/private-ddn/architecture/byoc.mdx mode=EXCERPT
<Thumbnail src="/img/deployment/private_ddn_byoc.png" alt="Private DDN Architecture BYOC " />
````
Now, we've converted these into structured Mermaid diagrams that DocsQL can parse and understand:
```mermaid
flowchart TD
%% Layout hints
%% Top-to-bottom: PromptQL Infra (top), Customer Infra (bottom)
%% ===== PromptQL Infrastructure …
```
> Chore: Replace arch ERDs with mermaid

- docs/_quickstart_template.mdx
- docs/how-to-build-with-promptql/_boilerplateInit.mdx
- docs/how-to-build-with-promptql/with-api-endpoints.mdx
- docs/how-to-build-with-promptql/with-apis-with-bulk-data.mdx
- docs/private-ddn/create-a-project-on-a-data-plane.mdx
- docs/private-ddn/ddn-workspace.mdx
- docs/project-configuration/tutorials/manage-multiple-environments.mdx
- docs/project-configuration/tutorials/work-with-multiple-repositories.mdx
- docs/project-configuration/tutorials/work-with-multiple-subgraphs.mdx
Previously, project creation requirements were inconsistently documented across our tutorial pages. Some had the info block, others referenced it indirectly, and the messaging varied slightly between pages.
````mdx path=docs/how-to-build-with-promptql/with-api-endpoints.mdx mode=EXCERPT
:::info Project Creation Requirements
To create a project, you'll need both a [Hasura Cloud account](https://cloud.hasura.io/signup) and have been granted
permission to create projects via our AI Catalyst Team. If you haven't been in touch, you can reach out
[here](https://promptql.io/book-demo) to get help.
:::
````
Now every tutorial that involves project creation gets the same clear, actionable requirements block right at the top. This eliminates confusion about prerequisites and ensures users know …
> Docs: Add admonition for permission requirements
