hasura/promptql-docs

src/css/custom.css
wiki/kitchen-sink.mdx

Custom CSS for PromptQL Appearance

---

docs/data-sources/connect-to-a-source.mdx
docs/data-sources/introspect-a-source.mdx
docs/data-sources/overview.mdx
docs/data-sources/troubleshooting.mdx

Rewrites the data sources section for PromtQL.
A question that still needs to be answered: which connectors are not ready/optimized for PromptQL?

Rewrite Data Sources section for PromptQL

---

k8s-manifest/cloudbuild.yaml
k8s-manifest/k8s/deployment.yaml
k8s-manifest/k8s/hpa.yaml
k8s-manifest/k8s/service.yaml
k8s-manifest/stage_cloudbuild.yaml

Updated manifest files for staging and prod deployments

---

docusaurus.config.ts

updated docs config to point to promptql docs

---

docs/private-ddn/architecture/byoc.mdx
docs/private-ddn/architecture/index.mdx
docs/private-ddn/architecture/self-hosted.mdx
docs/private-ddn/create-a-project-on-a-data-plane.mdx
docs/private-ddn/ddn-workspace.mdx
docs/private-ddn/overview.mdx

Rewrites the Private DDN section after a conversation with Shahidh.
We'll need new architecture diagrams as a follow-up shortly after Disrupt.

Rewrite Private DDN section

---

docs/data-modeling/data-modeling-workflows.mdx
docs/data-modeling/permissions.mdx
docs/deployment/hasura-ddn/incremental-builds.mdx
docs/reference/connectors/postgresql/native-operations/native-mutations.mdx
docs/reference/connectors/postgresql/native-operations/native-queries.mdx
docs/reference/connectors/postgresql/native-operations/vector-search.mdx
static/prismjs/ddn.js

- [Add logical separator line under permissions in the data-modeling section like in the how-to-build section.](https://sean-random-tweaks.promptql-docs.pages.dev/data-modeling/overview/)
- Replace `bash` and `sh` with `ddn` in relevant code blocks

Sean Random Tweaks

---

docs/_prereqs.mdx
docs/_quickstart_template.mdx
docs/data-modeling/data-modeling-workflows.mdx
docs/data-sources/connect-to-a-source.mdx
docs/how-to-build-with-promptql/with-amazon-athena.mdx
docs/how-to-build-with-promptql/with-amazon-redshift.mdx
docs/how-to-build-with-promptql/with-postgresql.mdx
docs/index.mdx
docs/quickstart.mdx

Heavier lifts coming in a separate PR.

Rob Read-Through and Edits

---

docusaurus.config.ts
src/theme/Navbar/Content/index.js

Algolia approved the DocSearch app. This PR adds back the configuration with new new ID, API key and reinstates the search bar.

Adds Algolia new app

---

src/css/custom.css

Hotfix logo 2

---

src/css/custom.css

Hotfix logo 3

---

src/css/custom.css

Nicer scroll logo

---

src/css/custom.css

Fix safari logos display

---

src/css/custom.css

Doc search fix highlighting text to be visible on active and hover.

Fixes highlighting text in search

---

docs/promptql-apis/execute-program-api.mdx

Adds information about AI primitives to the `/execute_program` docs.
These tools are all being called under the hood by PromptQL for various user-derived actions. Here, we're simply calling out that there's a (somewhat) consistent function signature in which inputs + system-generated instructions are passed and an artifact is returned. Additionally, we illustrate this with numerous examples to drive the point home while also connecting to the dots to custom business logic extending the tools available to PromptQL.
In a follow-up PR, there will be more dedicated information added around artifacts, which we'll link to from here.
[Executor API](https://robdominguez-doc-2686-improv.promptql-docs.pages.dev/promptql-apis/execute-program-api/)
A user should understand what the executor API is …

Add information about primitives

---

.github/workflows/run-changelog-for-field-teams.yml

Add workflow

---

.github/workflows/run-changelog-for-field-teams.yml
.gitignore

CI: Iterate on changelog

---

output/allDocs.md

This PR updates the LLM-generated markdown.

Chore: update LLM markdown

---

docs/data-modeling/iterate.mdx

Updates the iteration guide to focus on cases when rebuilds are necessary instead of only focusing on the underlying data model changing.
[Iteration guide](https://robdominguez-doc-2683-improv.promptql-docs.pages.dev/data-modeling/iterate/)

Update iteration guide

---

src/components/FRAMES/FRAMESAccuracyChart.tsx
src/components/FRAMES/FRAMESQuestionTable.tsx

Fixes visual issues with RAG question-accuracy table:
* Increases readability for the button(s) below the table
* Improves column-width stylings
* Makes the component responsive by dropping content to a single column on smaller screens
* Improves readability with background colors
[Affected section](https://robdominguez-fix-visual-regr.promptql-docs.pages.dev/reference/rag-hundred-percent-accuracy/#questions)

Fix visual regression rag accuracy

---

docs/kitchen-sink.mdx

Bring back the kitchen sink page
[Kitchen Sink](https://sean-doc-2820-bring-back-the.promptql-docs.pages.dev/kitchen-sink/)

Bring back the sink (Mini blitz branch merge)

---

docs/help/security.mdx
docs/index.mdx
src/components/CustomFooter/index.tsx
src/components/DemoGallery/index.tsx
src/components/Feedback/Feedback.tsx
src/css/custom.css
src/theme/DocRoot/Layout/Main/index.js

Largely, I've elected to not make changes to the Hasura » PromptQL language for various components and services until we have a better plan of action.
Instead, this PR intends to take care of some small semantic nits and more closely align the styling/state changes with what's in the promptql.io marketing site. These changes come after conversations with Shmo and Kai.

Mini-blitz readthrough

---

docusaurus.config.ts

Updates Algolia configuration in docusaurus.config.ts with new app id, api key, index. 
Index is populated and ready. 
docusaurus.config.ts

Update Algolia configuration in docusaurus.config.ts

---

src/components/CopyLlmText/index.tsx

Ports fix from hasura/ddn-docs#1008.

Fix: Webkit issue for llm copy

---

docs/project-configuration/promptql-config/providers.mdx

self explanatory
https://shahidhk-patch-1.promptql-docs.pages.dev/project-configuration/promptql-config/providers/#hasura

Add a note about Hasura LLM not being HIPAA complaint

---

docs/auth/jwt/jwt-configuration.mdx

As titled.
[JWT escaping](https://robdominguez-doc-3021-update.promptql-docs.pages.dev/auth/jwt/jwt-configuration/#jwt-claims-config-namespace)

Docs: Update JWT escaping

---

.github/workflows/sync-embeddings.yml

CI: Update automation endpoints to Private DDN

---

docs/capabilities.mdx
docs/index.mdx
docs/quickstart.mdx

Docs: Small nudges

---

docs/index.mdx

Docs: Update frontamtter for index

---

.github/workflows/weekly-docs-report.yml

Automated weekly DocsQL usage reporting that actually works without me having to remember to run it every Monday morning.
- Runs automatically every Monday at 9 AM UTC via cron schedule
- Generates comprehensive usage reports via PromptQL Threads API
- Posts formatted reports directly to Slack with conversation and message metrics
- Includes manual trigger option for ad-hoc reports with customizable parameters
Previously, tracking DocsQL usage meant manually running queries and cobbling together reports whenever someone asked "how's adoption looking?" Now we get consistent weekly insights delivered straight to Slack without lifting a finger.
````yaml path=.github/workflows/weekly-docs-report.yml mode=EXCERPT
name: Weekly DocsQL Usage Report
on:
schedule:
- cron: '0 9 * * 1'  # Every …
```

CI: Add weekly report

---

docs/deployment/hasura-ddn/ci-cd.mdx

Docs: Update CI/CD docs to use pql-ci-cd

---

docs/auth/permissions/authorization_rules.mdx

Authorization rules docs

---

docs/promptql-playground/artifacts.mdx

Docs: Add mentions for artifacts

---

docs/deployment/hasura-ddn/region-routing.mdx

Removed unsupported GCP regions from the documentation.

Update supported regions for Hasura DDN
